//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerlinClock.Classes.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BerlinClock.Classes.Res.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting color to string. Unexpected color .
        /// </summary>
        internal static string Error_Converting_Color_To_String_Unexpected_Color {
            get {
                return ResourceManager.GetString("Error_Converting_Color_To_String_Unexpected_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is not a valid date.
        /// </summary>
        internal static string Is_Not_A_Valid_Date {
            get {
                return ResourceManager.GetString("Is_Not_A_Valid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockRow: Value must be greater then 0.
        /// </summary>
        internal static string Value_must_be_greater_then_0 {
            get {
                return ResourceManager.GetString("Value_must_be_greater_then_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockRow: Value must be positive.
        /// </summary>
        internal static string Value_must_be_positive {
            get {
                return ResourceManager.GetString("Value_must_be_positive", resourceCulture);
            }
        }
    }
}
